package alilogs

import (
	"fmt"

	sls "github.com/galaxydi/go-loghub"
)

// MockClient is an autogenerated mock type for the AliLogAPI type
type MockClient struct {
	ErrType int
	Topic   string
	Logs    []*sls.Log
}

func NewMockClient() *MockClient {
	client := &MockClient{
		ErrType: 0,
		Topic:   "",
		Logs:    []*sls.Log{},
	}
	return client
}

// PutLogs provides a mock function with given fields: _a0
func (client *MockClient) PutLogs(lg *sls.LogGroup) error {
	switch client.ErrType {
	case 0:
		// no error
		client.Topic = lg.GetTopic()
		for _, v := range lg.GetLogs() {
			client.Logs = append(client.Logs, v)
		}
		return nil
	case 1:
		slsErr := &sls.Error{
			Code:    "InternalServerError",
			Message: "loghub service is not avaliable",
		}
		return slsErr
	default:
		err := fmt.Errorf("unknown error")
		return err
	}
}
