package alilogs

import (
	"fmt"

	sls "github.com/aliyun-fc/go-loghub"
)

type errorType int

const (
	NoError errorType = iota
	InternalServerError
	UnknownError
)

// MockClient is an autogenerated mock type for the AliLogAPI type
type MockClient struct {
	ErrType errorType
	Topic   string
	Logs    []*sls.Log
}

func NewMockClient() *MockClient {
	client := &MockClient{
		ErrType: NoError,
		Topic:   "",
		Logs:    []*sls.Log{},
	}
	return client
}

// PutLogs provides a mock function with given fields: _a0
func (client *MockClient) PutLogs(lg *sls.LogGroup) error {
	switch client.ErrType {
	case NoError:
		client.Topic = lg.GetTopic()
		client.Logs = append(client.Logs, lg.GetLogs()...)
		return nil
	case InternalServerError:
		slsErr := &sls.Error{
			Code:    "InternalServerError",
			Message: "loghub service is not avaliable",
		}
		return slsErr
	case UnknownError:
		return fmt.Errorf("Unknown error")
	default:
		return fmt.Errorf("Unknown error")
	}
}
